### ISSUE TITLE
能不能写一下使用教程，小白有点不知道怎么安装依赖啥的

### ISSUE THREAD

**Issue by Xunflash** [yxdragon/qq-snooker-helper#1]

**Comment by Xunflash** [comment]
知道怎么使用了，但是瞄准度实在太低了

**Comment by ChunSource** [comment]
兄弟，留个联系方式交流一下

**Comment by Xunflash** [comment]
> 兄弟，留个联系方式交流一下

QQ 1007006749

**Comment by Vinson-ch** [comment]
我的鼠标不会动怎么办

**Comment by IySANCamille** [comment]
最近在尝试学习程序控制，想问一下，qq桌球是如何截图到的呢？为什么我通过findwindow获取的句柄得到的位置一直是负的而且是固定的呢？？您是怎么获取截图的可以请教一下吗
